### ISSUE TITLE
svox fails to install

### ISSUE THREAD

**Issue by jul1u5** [sxyu/plenoctree#12]
The command `conda env create -f environment.yml` fails with the following output:
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/julius_m/miniconda3/envs/plenoctree/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4j3q1aav/svox_d94175d95f2e44f3af58d34c864072e7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4j3q1aav/svox_d94175d95f2e44f3af58d34c864072e7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4rfnzt2l
         cwd: /tmp/pip-install-4j3q1aav/svox_d94175d95f2e44f3af58d34c864072e7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4j3q1aav/svox_d94175d95f2e44f3af58d34c864072e7/setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9f/bd/12837d0f1589546e94786ece045d3250ada53bd5ee8a66234308c11b59f2/svox-0.2.32.tar.gz#sha256=b086aecbbe22f5d4c6941162290413b52ef763cd30a7d1e1e3e27edfc8309ad0 (from https://pypi.org/simple/svox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /home/julius_m/miniconda3/envs/plenoctree/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4j3q1aav/svox_2512b4322737469394e215e440a3fb07/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4j3q1aav/svox_2512b4322737469394e215e440a3fb07/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-oum785ux
         cwd: /tmp/pip-install-4j3q1aav/svox_2512b4322737469394e215e440a3fb07/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4j3q1aav/svox_2512b4322737469394e215e440a3fb07/setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7b/e9/46007938df43c9a51826dd56b69bc897b0216ce0c2d0082fd355721cf378/svox-0.2.31.tar.gz#sha256=24efe346fab6aa2fbbcd3fa83e961d9fdb5adff6eb8e8d2d88dcc955b461f639 (from https://pypi.org/simple/svox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /home/julius_m/miniconda3/envs/plenoctree/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4j3q1aav/svox_66aa37c3639140ca9e7933035cd95dad/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4j3q1aav/svox_66aa37c3639140ca9e7933035cd95dad/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-w8t7wafl
         cwd: /tmp/pip-install-4j3q1aav/svox_66aa37c3639140ca9e7933035cd95dad/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4j3q1aav/svox_66aa37c3639140ca9e7933035cd95dad/setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/92/bf2bff8c58f27c0481f7ad89dea4b2ac9d9637e4b5caf1d39be9ed702b37/svox-0.2.30.tar.gz#sha256=95f7bcf01ef1e9106f458f95261de439f1c91dc668184277d0463dd9687b2cb4 (from https://pypi.org/simple/svox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /home/julius_m/miniconda3/envs/plenoctree/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4j3q1aav/svox_7cbe926eb4ad472c920d471061d9f7f7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4j3q1aav/svox_7cbe926eb4ad472c920d471061d9f7f7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6ncndzwq
         cwd: /tmp/pip-install-4j3q1aav/svox_7cbe926eb4ad472c920d471061d9f7f7/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4j3q1aav/svox_7cbe926eb4ad472c920d471061d9f7f7/setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c1/83/13373194ee8823735cd1c5ff9bbc73d2d6ca7e61494d4ae81d8d514680c3/svox-0.2.29.tar.gz#sha256=5a7462665bc106be11817e1d0e3e0acf53dc9c6c082342de8ffcd02799b17bbf (from https://pypi.org/simple/svox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /home/julius_m/miniconda3/envs/plenoctree/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4j3q1aav/svox_20700ac0eded45488f2b17800ed403b8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4j3q1aav/svox_20700ac0eded45488f2b17800ed403b8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ffwllv9k
         cwd: /tmp/pip-install-4j3q1aav/svox_20700ac0eded45488f2b17800ed403b8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4j3q1aav/svox_20700ac0eded45488f2b17800ed403b8/setup.py", line 4, in <module>
        from torch.utils.cpp_extension import BuildExtension, CUDAExtension
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5c/37/e479cb95e48ffe041f806ffc1a6720cddf57da281eed248116e7bc384685/svox-0.2.28.tar.gz#sha256=cbc3d4dcf834e8bb8ec90331f8a8c92dc23472561f1d905e8db638e6e44410a8 (from https://pypi.org/simple/svox/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement svox>=0.2.28 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.2.23, 0.2.24, 0.2.25, 0.2.26, 0.2.27, 0.2.28, 0.2.29, 0.2.30, 0.2.31, 0.2.32)
ERROR: No matching distribution found for svox>=0.2.28

Ran pip subprocess with arguments:
['/home/julius_m/miniconda3/envs/plenoctree/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/julius_m/code/plenoctree/condaenv.h9g_s1_e.requirements.txt']
Pip subprocess output:
Collecting dotmap
  Using cached dotmap-1.3.24-py3-none-any.whl (11 kB)
Collecting imageio
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting imageio-ffmpeg
  Using cached imageio_ffmpeg-0.4.5-py3-none-manylinux2010_x86_64.whl (26.9 MB)
Collecting ipdb
  Using cached ipdb-0.13.9.tar.gz (16 kB)
Collecting pretrainedmodels
  Using cached pretrainedmodels-0.7.4.tar.gz (58 kB)
Collecting lpips
  Using cached lpips-0.1.4-py3-none-any.whl (53 kB)
Collecting jax==0.2.9
  Using cached jax-0.2.9.tar.gz (551 kB)
Collecting jaxlib>=0.1.57
  Using cached jaxlib-0.1.71-cp38-none-manylinux2010_x86_64.whl (50.9 MB)
Collecting flax>=0.3.1
  Using cached flax-0.3.5-py3-none-any.whl (193 kB)
Collecting opencv-python>=4.4.0
  Using cached opencv_python-4.5.3.56-cp38-cp38-manylinux2014_x86_64.whl (49.9 MB)
Collecting Pillow>=7.2.0
  Using cached Pillow-8.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
Collecting pyyaml>=5.3.1
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting tensorboard>=2.4.0
  Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
Collecting tensorflow>=2.3.1
  Using cached tensorflow-2.6.0-cp38-cp38-manylinux2010_x86_64.whl (458.4 MB)
Collecting pymcubes
  Using cached PyMCubes-0.1.2-cp38-cp38-manylinux2010_x86_64.whl (282 kB)
Collecting svox>=0.2.28
  Using cached svox-0.2.32.tar.gz (43 kB)
  Using cached svox-0.2.31.tar.gz (40 kB)
  Using cached svox-0.2.30.tar.gz (37 kB)
  Using cached svox-0.2.29.tar.gz (36 kB)
  Using cached svox-0.2.28.tar.gz (36 kB)

failed

CondaEnvException: Pip failed
```

**System Information**
OS: Ubuntu 20.04.1 (Linux 5.11.0-27-generic)

**Comment by Realitian** [comment]
you can install svox from source code.

**Comment by liusang** [comment]
use PyTorch 1.7

**Comment by joey0320** [comment]
Did you guys fix this issue?

**Comment by zhywanna** [comment]
> Did you guys fix this issue?

just move `svox` down after other packages were downloaded

**Comment by ChikaYan** [comment]
In my case I had to install PyTorch 1.7.1 from pip -- installing from conda doesn't work for some reason.

`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`
